### ISSUE TITLE
Babel compiled code error

### ISSUE THREAD

**Issue by neonmaccca** [idflores/twitch-irc#1]
The following code is causing an unhandled error.

`function chat(b)
{
    var c=1<arguments.length&&void 0!==arguments[1]?arguments[1]:null;
    try{
        if(null===c){
        var d=this.channel.length-1;
        if(-1==d)
            throw'ERROR: You must join a channel first';
        this.client.write('PRIVMSG #'+this.channel[d].toLowerCase()+' :'+b+'\r\n');var f=new _msg2.default;f.meta_host=this.username,f.host='tmi.twitch.tv',
f.tag='PRIVMSG',
f.channel=this.channel[d],
f.message=message,`

surley `f.message=message` should be `f.message=b`

seems the compiled code is wrong, error goes away if i manually edit the compiled code

**Comment by israelflores8789** [comment]
Hmm... just did a quick check. I think there may be a scope error. Technically, `message` is `b` and should be assigned to `f.message`. The variable name `message` got changed to `b` at compile time but... not all of them. *sigh* that's Babel for ya. Let me see what I can do on a hotfix.

**Comment by israelflores8789** [comment]
Version 1.0.4 with commit 1adf04e should fix the issue. It turned out to be a spelling error with message written as `messsage`. Closing the issue.

**Comment by neonmaccca** [comment]
Many thanks for this

**Comment by neonmaccca** [comment]
Also has this been pushed to npm yet?

**Comment by israelflores8789** [comment]
NPM was updated to version [![Node Version](https://img.shields.io/badge/npm-1.0.4-blue.svg?style=flat-square)](https://www.npmjs.com/package/twitch-irc-lite) before closing the issue. Let me know if you have any issues with it.

**Comment by neonmaccca** [comment]
Will do many thanks again.
